language: r
dist: trusty
sudo: false
cache:
  packages: yes
  directories:
    - $HOME/bin
    
branches:
    only:
        - source
        
r_github_packages:
    - yihui/xfun
    - yihui/xaringan
    - rstudio/blogdown

before_script:
    - Rscript -e 'blogdown::install_hugo()'

script:
    - Rscript -e 'blogdown::build_site()'

deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_PAT
    on:
        branch: source
    local_dir: public
    target_branch: master
    verbose: true

