language: r
cache: packages
branches:
    only:
        - source
r_github_packages:
    - yihui/xaringan
    - yihui/xfun
    - rstudio/blogdown

before_script:
    - Rscript -e 'blogdown::install_hugo()'

script:
    - Rscript -e 'blogdown::build_site()'

deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_PAT
    on:
        branch: source
    local_dir: public
    keep-history: true
    target_branch: master
