---
title: "Chanyub Park"
image: "https://media-exp1.licdn.com/dms/image/C5103AQHEnbVyKFc5tQ/profile-displayphoto-shrink_400_400/0/1580143693466?e=1617235200&v=beta&t=zUGCfjK8B_814mdTweoREsyb7nIOI0VGNSN4NbqQVHQ"
links:
  - label: LinkedIn
    url: "https://linkedin.com/in/chanyubpark/"
  - label: Twitter
    url: "https://twitter.com/mrchypark_"
  - label: GitHub
    url: "https://github.com/mrchypark"
  - label: Email
    url: "mailto:mrchypark@gmail.com"
  - label: Site
    url: "https://mrchypark.github.io"
output:
  postcards::trestles
---
 
[한글][kr]

I'm a big fan of **R** & **docker** working on data-related tasks.

I'm interested in research about **text**.

I have only recently decided to study **go language** and **vue.js**.

I am more interested in people being able to handle data more easily and eventually to facilitate data-based communication.

For most of my accounts, contacts and profiles, please see the links on the left sidebar.

###  activity

- I crated and manage [ForkonLP][forkonlp], a nonprofit organization that distributes data for Korean Studies .
    - Typically, organization creates and manages [N2H4][N2H4], [DNH4][DNH4], [presidentSpeechKr][presidentSpeechKr].
- I am contributing to the R ecosystem
    1. Create a package, register it in [cran][등록] and manage it (put it in [github][repo] first).
    2. Try to [contribute][기여] to another package as much as possible.
    3. I ask and answer questions about R and data analysis related groups such as [Data Analytics Community in Korea][dc].
    4. I make and share R related [materials][Materials].
    5. I'm working on [translation][번역] and writing.

[kr]: https://mrchypark.github.io/about/
[forkonlp]: https://forkonlp.github.io/
[repo]: https://github.com/mrchypark?tab=repositories
[기여]: https://github.com/pulls?utf8=%E2%9C%93&q=author%3Amrchypark+
[dc]: https://www.facebook.com/groups/datacommunity
[Materials]: https://mrchypark.github.io/material/
[번역]: http://www.aladin.co.kr/shop/wproduct.aspx?ItemId=149310215
[등록]: https://cran.r-project.org/web/packages/ubci/index.html
[N2H4]: https://forkonlp.github.io/N2H4/
[DNH4]: https://forkonlp.github.io/DNH4/
[presidentSpeechKr]: https://forkonlp.github.io/presidentSpeechKr/
